name: TruffleHog Secret Scanner

on:
  pull_request:  # Runs on pull requests
  push:          # Runs on every push
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensures previous commit is available for comparison

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: "--regex --entropy=True"  # Uses regex scanning + entropy analysis
