name: TruffleHog Secret Scanner

on:
  pull_request:  # Run on every PR
  push:          # Run on every push
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is available

      - name: Run TruffleHog on Filesystem
        run: |
          docker run --rm -v $(pwd):/src ghcr.io/trufflesecurity/trufflehog:latest filesystem /src --json --only-verified=false

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Handle Failure
        if: failure()
        run: echo "Secrets detected! Check the TruffleHog report." && exit 1
