name: TruffleHog Secret Scanner

on:
  pull_request:  # Runs on PRs
  push:          # Runs on every push
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to fix merge base issues

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: "."  # Scan entire repository

      - name: Handle Failure
        if: failure()
        run: echo "Secrets detected! Check the TruffleHog report." && exit 1
