name: TruffleHog Secret Scanner

on:
  pull_request:  # Runs on every pull request
  push:          # Runs on every push
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to avoid Git issues

      - name: Run TruffleHog
        run: |
          docker run --rm -v $(pwd):/src ghcr.io/trufflesecurity/trufflehog:latest filesystem /src --no-verify
